### PR TITLE
Setup for multiple NIC

### PR DESCRIPTION
**Pull request by lukyky414**
General clean of playbooks
Simplify jinja templates: put all arguments in a single file `arguments.j2`
→ /!\ Space after `{% include 'arguments.j2' %} ` is very important.
Support for multiple NIC without limit
Change name in README
grub.cfg-single-ppc64.j2 unused
Added playbook compatibility for Debian / Ubuntu with installed packages

### CODE REVIEW

**Comment by lukyky414** [comment]
Oops, there is some typo on playbooks:
`Relace` should be `Replace`.

**Comment by chuckersjp** [comment]
Looks great!

However, can I ask why you have removed the PPC64 things?  There are still some references to it
but it doesn't look like they will be used.

Demand for PPC64 is likely small but it is there which is why it was included.

**Comment by lukyky414** [comment]
Hello,

The PPC64 is still there. The file 'grub.cfg-single-ppc64.j2' was exactly the same as 'grub.cfg-single.j2'.
The only difference using ppc64 is:
- no isolinux
- grub.cfg location (`/tmp/rhcos-iso/EFI/redhat/grub.cfg` on x86_64, `/tmp/rhcos-iso/boot/grub/grub.cfg` on ppc64le)
- the command generating the iso.

Difference are only in the playbook, not in the jinja template.



I may be wrong with my analyse, I did not use a single time the ppc64le solution.

**Comment by chuckersjp** [comment]
Sorry, got distracted and then forgot about this.

Yeah it looks like the jinja templates differ only by a new line at the end.  Let me take one more look over this.

**Comment by chuckersjp** [comment]
Yeah, looks good.  Thanks a lot for this!  Certainly helps a lot of the logic.

**Pull request merged**
